
# Server configuration
server:
  port: 8082


spring:
  application:
    name: subscription

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  # JPA / Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway configuration for database migrations
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration


# Stripe API configuration
stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# Logging configuration
logging:
  level:
    org.springframework: INFO
    com.niyiment.subscription: DEBUG
    org.hibernate.SQL: DEBUG
